export const COLLECTIONS_WITH_SOURCES_KEY = 'collections-with-sources'
export const CHAT_USAGE_KEY = 'chat-usage'
export const CITATIONS_KEY = 'citations'
export const SOURCE_LINKS_KEY = 'source-links'
export const CHATS_KEY = 'chats'
